language: go

go:
  - 1.7.4
  - tip

before_install:
  - go get -u github.com/distributeddesigns/currency
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/petar/GoLLRB/llrb
  - gometalinter --install

install:
  - go build .

script:
  - go test -v -cover
  - gometalinter --config=.gometalinterrc ./...

notifications:
  email: false
